# Copyright (c) 2015-2019, RTE (http://www.rte-france.com)
# See AUTHORS.txt
# All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0
#
# This file is part of Dynawo, an hybrid C++/Modelica open source time domain
# simulation tool for power systems.
#
# Continous Integration setup for Dynawo.

language: cpp

notifications:
  email:
    recipients:
      - gautier.bureau@rte-france.com
      - florentine.rosiere@rte-france.com
    on_success: never
    on_failure: always

jobs:
  include:
    # - stage: build
    #   os: linux
    #   dist: trusty
    #   services: docker
    #   sudo: required
    #   env: DYNAWO_BUILD_TYPE=Release DYNAWO_CXX11_ENABLED=NO DYNAWO_COMPILER=GCC DYNAWO_LIBRARY_TYPE=SHARED DISTRIBUTION=fedora
    #   install:
    #     - source define_variables_fedora.sh
    #     - ./install_stage_fedora.sh
    #   script:
    #     - ./build_stage_fedora.sh
    # - stage: build
    #   os: linux
    #   dist: trusty
    #   services: docker
    #   sudo: required
    #   env: DYNAWO_BUILD_TYPE=Release DYNAWO_CXX11_ENABLED=YES DYNAWO_COMPILER=GCC DYNAWO_LIBRARY_TYPE=SHARED DISTRIBUTION=fedora
    #   install:
    #     - source define_variables_fedora.sh
    #     - ./install_stage_fedora.sh
    #   script:
    #     - ./build_stage_fedora.sh
    # - stage: build
    #   os: linux
    #   dist: trusty
    #   services: docker
    #   sudo: required
    #   env: DYNAWO_BUILD_TYPE=Debug DYNAWO_CXX11_ENABLED=NO DYNAWO_COMPILER=GCC DYNAWO_LIBRARY_TYPE=SHARED DISTRIBUTION=fedora
    #   install:
    #     - source define_variables_fedora.sh
    #     - ./install_stage_fedora.sh
    #   script:
    #     - ./build_stage_fedora.sh
    # - stage: build
    #   os: linux
    #   dist: trusty
    #   services: docker
    #   sudo: required
    #   env: DYNAWO_BUILD_TYPE=Debug DYNAWO_CXX11_ENABLED=YES DYNAWO_COMPILER=GCC DYNAWO_LIBRARY_TYPE=SHARED DISTRIBUTION=fedora
    #   install:
    #     - source define_variables_fedora.sh
    #     - ./install_stage_fedora.sh
    #   script:
    #     - ./build_stage_fedora.sh
    # - stage: build
    #   os: linux
    #   dist: trusty
    #   services: docker
    #   sudo: required
    #   env: DYNAWO_BUILD_TYPE=Release DYNAWO_CXX11_ENABLED=NO DYNAWO_COMPILER=GCC DYNAWO_LIBRARY_TYPE=STATIC DISTRIBUTION=fedora
    #   install:
    #     - source define_variables_fedora.sh
    #     - ./install_stage_fedora.sh
    #   script:
    #     - ./build_stage_fedora.sh
    # - stage: build
    #   os: linux
    #   dist: trusty
    #   services: docker
    #   sudo: required
    #   env: DYNAWO_BUILD_TYPE=Release DYNAWO_CXX11_ENABLED=YES DYNAWO_COMPILER=GCC DYNAWO_LIBRARY_TYPE=STATIC DISTRIBUTION=fedora
    #   script:
    #     - ./build_stage_fedora.sh
    # - stage: build
    #   os: linux
    #   dist: trusty
    #   services: docker
    #   sudo: required
    #   env: DYNAWO_BUILD_TYPE=Debug DYNAWO_CXX11_ENABLED=NO DYNAWO_COMPILER=GCC DYNAWO_LIBRARY_TYPE=STATIC DISTRIBUTION=fedora
    #   install:
    #     - source define_variables_fedora.sh
    #     - ./install_stage_fedora.sh
    #   script:
    #     - ./build_stage_fedora.sh
    # - stage: build
    #   os: linux
    #   dist: trusty
    #   services: docker
    #   sudo: required
    #   env: DYNAWO_BUILD_TYPE=Debug DYNAWO_CXX11_ENABLED=YES DYNAWO_COMPILER=GCC DYNAWO_LIBRARY_TYPE=STATIC DISTRIBUTION=fedora
    #   install:
    #     - source define_variables_fedora.sh
    #     - ./install_stage_fedora.sh
    #   script:
    #     - ./build_stage_fedora.sh
    # - stage: build
    #   os: linux
    #   dist: trusty
    #   services: docker
    #   sudo: required
    #   env: DYNAWO_BUILD_TYPE=Release DYNAWO_CXX11_ENABLED=NO DYNAWO_COMPILER=CLANG DYNAWO_LIBRARY_TYPE=SHARED DISTRIBUTION=fedora
    #   install:
    #     - source define_variables_fedora.sh
    #     - ./install_stage_fedora.sh
    #   script:
    #     - ./build_stage_fedora.sh
    # - stage: build
    #   os: linux
    #   dist: trusty
    #   services: docker
    #   sudo: required
    #   env: DYNAWO_BUILD_TYPE=Release DYNAWO_CXX11_ENABLED=YES DYNAWO_COMPILER=CLANG DYNAWO_LIBRARY_TYPE=SHARED DISTRIBUTION=fedora
    #   install:
    #     - source define_variables_fedora.sh
    #     - ./install_stage_fedora.sh
    #   script:
    #     - ./build_stage_fedora.sh
    # - stage: build
    #   os: linux
    #   dist: trusty
    #   services: docker
    #   sudo: required
    #   env: DYNAWO_BUILD_TYPE=Debug DYNAWO_CXX11_ENABLED=NO DYNAWO_COMPILER=CLANG DYNAWO_LIBRARY_TYPE=SHARED DISTRIBUTION=fedora
    #   install:
    #     - source define_variables_fedora.sh
    #     - ./install_stage_fedora.sh
    #   script:
    #     - ./build_stage_fedora.sh
    # - stage: build
    #   os: linux
    #   dist: trusty
    #   services: docker
    #   sudo: required
    #   env: DYNAWO_BUILD_TYPE=Debug DYNAWO_CXX11_ENABLED=YES DYNAWO_COMPILER=CLANG DYNAWO_LIBRARY_TYPE=SHARED DISTRIBUTION=fedora
    #   install:
    #     - source define_variables_fedora.sh
    #     - ./install_stage_fedora.sh
    #   script:
    #     - ./build_stage_fedora.sh
    # - stage: build
    #   os: linux
    #   dist: trusty
    #   services: docker
    #   sudo: required
    #   env: DYNAWO_BUILD_TYPE=Release DYNAWO_CXX11_ENABLED=NO DYNAWO_COMPILER=CLANG DYNAWO_LIBRARY_TYPE=STATIC DISTRIBUTION=fedora
    #   install:
    #     - source define_variables_fedora.sh
    #     - ./install_stage_fedora.sh
    #   script:
    #     - ./build_stage_fedora.sh
    # - stage: build
    #   os: linux
    #   dist: trusty
    #   services: docker
    #   sudo: required
    #   env: DYNAWO_BUILD_TYPE=Release DYNAWO_CXX11_ENABLED=YES DYNAWO_COMPILER=CLANG DYNAWO_LIBRARY_TYPE=STATIC DISTRIBUTION=fedora
    #   install:
    #     - source define_variables_fedora.sh
    #     - ./install_stage_fedora.sh
    #   script:
    #     - ./build_stage_fedora.sh
    # - stage: build
    #   os: linux
    #   dist: trusty
    #   services: docker
    #   sudo: required
    #   env: DYNAWO_BUILD_TYPE=Debug DYNAWO_CXX11_ENABLED=NO DYNAWO_COMPILER=CLANG DYNAWO_LIBRARY_TYPE=STATIC DISTRIBUTION=fedora
    #   install:
    #     - source define_variables_fedora.sh
    #     - ./install_stage_fedora.sh
    #   script:
    #     - ./build_stage_fedora.sh
    # - stage: build
    #   os: linux
    #   dist: trusty
    #   services: docker
    #   sudo: required
    #   env: DYNAWO_BUILD_TYPE=Debug DYNAWO_CXX11_ENABLED=YES DYNAWO_COMPILER=CLANG DYNAWO_LIBRARY_TYPE=STATIC DISTRIBUTION=fedora
    #   install:
    #     - source define_variables_fedora.sh
    #     - ./install_stage_fedora.sh
    #   script:
    #     - ./build_stage_fedora.sh
    # - stage: build
    #   os: linux
    #   dist: trusty
    #   services: docker
    #   sudo: required
    #   env: DYNAWO_BUILD_TYPE=Release DYNAWO_CXX11_ENABLED=YES DYNAWO_COMPILER=GCC DYNAWO_LIBRARY_TYPE=SHARED DISTRIBUTION=fedora
    #   install:
    #     - source define_variables_fedora.sh
    #     - ./install_stage_fedora.sh
    #   script:
    #     - docker exec $dynawo_env $dynawo_om_env_local $dynawo_env_url dynawo_travis_container bash -c "$BUILD_OMC_COMMAND"
    # - stage: build
    #   os: linux
    #   dist: trusty
    #   services: docker
    #   sudo: required
    #   env: DYNAWO_BUILD_TYPE=Release DYNAWO_CXX11_ENABLED=YES DYNAWO_COMPILER=GCC DYNAWO_LIBRARY_TYPE=SHARED DISTRIBUTION=bionic
    #   install:
    #     - source define_variables_bionic.sh
    #     - ./install_stage_bionic.sh
    #   script:
    #     - ./build_stage_bionic.sh
    - stage: build
      os: osx
      osx_image: xcode10.3
      env: DYNAWO_BUILD_TYPE=Release DYNAWO_CXX11_ENABLED=YES DYNAWO_COMPILER=CLANG DYNAWO_LIBRARY_TYPE=SHARED
      install:
        - source define_variables_macos.sh
        - ./install_stage_macos.sh
      script:
        - ./build_stage_macos.sh
    # - stage: build
    #   os: osx
    #   osx_image: xcode10.3
    #   env: DYNAWO_BUILD_TYPE=Debug DYNAWO_CXX11_ENABLED=YES DYNAWO_COMPILER=CLANG DYNAWO_LIBRARY_TYPE=SHARED
    #   install:
    #     - source define_variables_macos.sh
    #     - ./install_stage_macos.sh
    #   script:
    #     - ./build_stage_macos.sh
    # - stage: build
    #   os: osx
    #   osx_image: xcode10.3
    #   env: DYNAWO_BUILD_TYPE=Release DYNAWO_CXX11_ENABLED=YES DYNAWO_COMPILER=CLANG DYNAWO_LIBRARY_TYPE=STATIC
    #   install:
    #     - source define_variables_macos.sh
    #     - ./install_stage_macos.sh
    #   script:
    #     - ./build_stage_macos.sh
    # - stage: build
    #   os: osx
    #   osx_image: xcode10.3
    #   env: DYNAWO_BUILD_TYPE=Debug DYNAWO_CXX11_ENABLED=YES DYNAWO_COMPILER=CLANG DYNAWO_LIBRARY_TYPE=STATIC
    #   install:
    #     - source define_variables_macos.sh
    #     - ./install_stage_macos.sh
    #   script:
    #     - ./build_stage_macos.sh
